import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

import './globals.css';
import { cn } from '@/helpers/classNames';
import CookieConsent from '@/components/CookieConsent/CookieConsent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type RootLayoutProps = {
  children: React.ReactNode;
}

/**
 * Function representing the RootLayout component.
 *
 * @returns RootLayout component
 */
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn('flex min-h-screen flex-col items-center justify-center gap-y-3', inter.className)}>
        {children}

        <CookieConsent />
      </body>
    </html>
  );
}
